# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/**'
      - 'pom*.xml'
    branches:
      - alpha001
      - 'chapter**'
  pull_request:
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/**'
      - 'pom*.xml'
    branches:
      - alpha001
      - 'chapter**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: actions-setup-redis
      # You may pin to the exact commit or the version.
      # uses: shogo82148/actions-setup-redis@f168880de5407eeb262957436a2ed697af41cdb4
      uses: shogo82148/actions-setup-redis@v1.9.1
    - name: Build with Maven
      run: mvn -B verify --file pom_test.xml
